language: ruby
rvm:
- 2.2
cache: bundler
branches:
  only:
  - master
  - stable
install:
- bundle install
before_script:
- chmod +x checkout-and-build.sh
- chmod +x deploy.sh
script:
- "./checkout-and-build.sh"
- "./deploy.sh"
env:
  global:
  - secure: qD8whULaGh2K8OueTbhmywR5AiV8WrYKfgB6qQt4zSz9HkjmDCN0oY4xj0+8J5AQWONDWHnx/SuuX4P25Dl4Mgo1BYWScZOIpNH6TkWFK60nKZWc8TI8VHuLEOhXvALgGWn+tbYTxwFjYQ/51UcFa2j1JnFpSyppuuLhfqVrowkO1pOBiR0REt7s1zXTxq4dzA6ZuU5OeSmn6UKSupDdIou5UB7IoJUonkFLTV4h0geJsvyyD61AWdhptdKHHfivNd17VF78+oVN+h2UpOnISiTJwSZKHjuwN4h2S/zgADU+lT2XalBP2oPmRZD0NPJifcHfyKUgDHdtCdnt96vijqhoODUfZspj8Z2kzJe2lvbV9mT/97RkqNw4HyRR5XwpMDcS/FfqIlRXz88rTW7b+RSMNkXmAw1Xw+w/SGm4a4vGQ2sBZTtIgQQNb4zdSlkEFsnzkOK68JV7WH/K+QjR1AOiqgUXf510M1b9OEsOL7Rtvgiy+75sowCzI/T6OY72niTstVMEtKtaYkaYRQia6FdlMUfNy+wuEy1gyn91G77aHv+VlojegabIrr3j+oU6xxTgWDdMj1bMz4sSq4B+NdIHBUpz2gBRU83jkqfmUHullkXlmFSRAxUZVoL/pQ9CviKH7j0THhE4TLUwz0jFsp8Jp0CKEB0l7cH+JDvRHyE=
