sudo: false
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.5.3
bundler_args: --without development
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
branches:
  only:
    - gh-pages
jobs:
  include:
    - stage: Test
      before_script:
        - npm install -g sass-lint htmllint-cli markdownlint-cli
      script:
        - JEKYLL_ENV=bundle exec jekyll build
        - htmllint _includes/stripped_markdown.html
        - markdownlint _posts _drafts _pages README.md
        - sass-lint --verbose --no-exit
    - stage: Github Release
      script:
        - JEKYLL_ENV=bundle exec jekyll build
      deploy:
        provider: pages
        local-dir: ./_site
        target-branch: master
        name: Travis Deployment Bot
        email: deploy@travis-ci.org
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: gh-pages
