# Site settings
author: Levi Leal
title: Levi Leal
description: "&ltsome tag here /&gt"
email: leviplj@gmail.com
baseurl: ""
url: "levileal.me"


# Social
github: https://github.com/leviplj
linkedin: https://linkedin.com/in/leviplj
twitter: https://twitter.com/jLeviLeal

# Build settings
destination: _site
markdown: kramdown
permalink: /blog/:title
sass:
  style: compressed
exclude: ['README.md', "*.sh", "Gemfile"]