# Site settings
author: Levi Leal
title: Levi Leal
description: "No description yet"
email: leviplj@gmail.com
baseurl: ""
url: "levileal.me"


# Social
github: https://github.com/leviplj


#Build settings
destination: _site
markdown: kramdown
permalink: /blog/:title
sass:
  style: compressed
exclude: ['README.md', "*.sh", "Gemfile"]